CREATE DATABASE PRACTICES;
CREATE TABLE  TBLPRODUCT
(
PRD_ID INT AUTO_INCREMENT,
PRD_NAME VARCHAR(30),
RECOMMENDED_PRICE VARCHAR(30),
CATEGORY VARCHAR(30),
PRIMARY KEY(PRD_ID)
);
USE PRACTICES;
create TABLE TBLCUSTOMER
(
CUSTOMERID INT auto_increment,
FIRSTNAME VARCHAR(30),
LASTNAME VARCHAR(30),
CITY VARCHAR(30),
STATE VARCHAR(30),
ZIPCODE VARCHAR(30),
PRIMARY KEY(CUSTOMERID)
);
CREATE TABLE SALES
(
SALES_ID int auto_increment,
PRD_ID int,
CUST_ID int,
SALESPRICE VARCHAR(30) ,
SALESDATES DATE,
primary key(SALES_ID),
foreign key(PRD_ID) references TBLPRODUCT(PRD_ID),
foreign key(CUST_ID) references TBLCUSTOMER(CUSTOMERID)
);